theme: jekyll-theme-cayman
title: Annotated Epigraphic Corpus of Ancient Italy

github:
  vademecum_url: https://reubenjpitts.github.io/Annotated-Epigraphic-Corpus-of-Ancient-Italy/vademecum
  overview_url: https://reubenjpitts.github.io/Annotated-Epigraphic-Corpus-of-Ancient-Italy
