theme: jekyll-theme-cayman
title: Annotated Epigraphic Corpus of Ancient Italy

github:
  vademecum_url: https://reubenjpitts.github.io/Corpus-of-the-Epigraphy-of-the-Italian-Peninsula-in-the-1st-Millennium-BCE/vademecum
  overview_url: https://reubenjpitts.github.io/Corpus-of-the-Epigraphy-of-the-Italian-Peninsula-in-the-1st-Millennium-BCE
