theme: jekyll-theme-cayman
title: Annotated Epigraphic Corpus of Ancient Italy
show_downloads: true

github:
  zip_url: https://reubenjpitts.github.io/Annotated-Epigraphic-Corpus-of-Ancient-Italy/vademecum
